.TH "Event" 3 "Wed Jan 4 2017" "Stoched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Event \- Class EVENT holds a user-specified event, namely set of functions and associated rate\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvent\fP ()"
.br
.RI "Default constructor for \fBEvent\fP\&. "
.ti -1c
.RI "\fB~Event\fP ()"
.br
.RI "Destructor of \fBEvent\fP\&. "
.ti -1c
.RI "void \fBaddFunction\fP (string function, string variables)"
.br
.RI "Add a function parser to the function array\&. "
.ti -1c
.RI "double \fBuseFunction\fP (int iFunction, double *args)"
.br
.RI "Evaluate function stored at specified spot in the function array\&. "
.ti -1c
.RI "void \fBsetRate\fP (string function, string variables)"
.br
.RI "Set equation for rateFunction\&. "
.ti -1c
.RI "double \fBgetRate\fP (double *args)"
.br
.RI "Return rate to user based on values of the state array\&. "
.ti -1c
.RI "int \fBgetSize\fP ()"
.br
.RI "Return size of event, namely number of functions, to user\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBeventName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class EVENT holds a user-specified event, namely set of functions and associated rate\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Event::Event ()"

.PP
Default constructor for \fBEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIeq_count\fP is the size of the function array 
.br
\fIfunctionArray\fP contains all user-specified FunctionParsers that govern event 
.RE
.PP
\fBReturns:\fP
.RS 4
nothing 
.RE
.PP

.SS "Event::~Event ()"

.PP
Destructor of \fBEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
nothing 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Event::addFunction (string function, string variables)"

.PP
Add a function parser to the function array\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunction\fP is a string used to generate a \fBFunctionParser\fP object 
.br
\fIvariables\fP is a string used to generate a \fBFunctionParser\fP object 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "double Event::getRate (double * stateArray)"

.PP
Return rate to user based on values of the state array\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstateArray\fP is a double array specifying variable values of function 
.RE
.PP
\fBReturns:\fP
.RS 4
evaluated rateFunction as a double 
.RE
.PP

.SS "int Event::getSize ()"

.PP
Return size of event, namely number of functions, to user\&. 
.PP
\fBParameters:\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
size of event, namely number of functions, as an int 
.RE
.PP

.SS "void Event::setRate (string function, string variables)"

.PP
Set equation for rateFunction\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunction\fP is a string used for parsing rateFunction 
.br
\fIvariables\fP is a string used for parsing rateFunction 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "double Event::useFunction (int iFunction, double * stateArray)"

.PP
Evaluate function stored at specified spot in the function array\&. 
.PP
\fBParameters:\fP
.RS 4
\fIiFunction\fP is an int that indexes function array 
.br
\fIstateArray\fP is a double array specifying variable values of function 
.RE
.PP
\fBReturns:\fP
.RS 4
evaluated functionParser as a double 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Stoched from the source code\&.
