.TH "FunctionParserBase< Value_t >" 3 "Wed Jan 4 2017" "Stoched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionParserBase< Value_t >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFunctionWrapper\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBParseErrorType\fP { \fBSYNTAX_ERROR\fP =0, \fBMISM_PARENTH\fP, \fBMISSING_PARENTH\fP, \fBEMPTY_PARENTH\fP, \fBEXPECT_OPERATOR\fP, \fBOUT_OF_MEMORY\fP, \fBUNEXPECTED_ERROR\fP, \fBINVALID_VARS\fP, \fBILL_PARAMS_AMOUNT\fP, \fBPREMATURE_EOS\fP, \fBEXPECT_PARENTH_FUNC\fP, \fBUNKNOWN_IDENTIFIER\fP, \fBNO_FUNCTION_PARSED_YET\fP, \fBFP_NO_ERROR\fP }"
.br
.ti -1c
.RI "typedef Value_t \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef Value_t(* \fBFunctionPtr\fP) (const Value_t *)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBParse\fP (const char *Function, const std::string &Vars, bool useDegrees=false)"
.br
.ti -1c
.RI "int \fBParse\fP (const std::string &Function, const std::string &Vars, bool useDegrees=false)"
.br
.ti -1c
.RI "void \fBsetDelimiterChar\fP (char)"
.br
.ti -1c
.RI "const char * \fBErrorMsg\fP () const"
.br
.ti -1c
.RI "ParseErrorType \fBGetParseErrorType\fP () const"
.br
.ti -1c
.RI "Value_t \fBEval\fP (const Value_t *Vars)"
.br
.ti -1c
.RI "int \fBEvalError\fP () const"
.br
.ti -1c
.RI "bool \fBAddConstant\fP (const std::string &name, Value_t value)"
.br
.ti -1c
.RI "bool \fBAddUnit\fP (const std::string &name, Value_t value)"
.br
.ti -1c
.RI "bool \fBAddFunction\fP (const std::string &name, FunctionPtr, unsigned paramsAmount)"
.br
.ti -1c
.RI "bool \fBAddFunction\fP (const std::string &name, \fBFunctionParserBase\fP &)"
.br
.ti -1c
.RI "template<typename DerivedWrapper > bool \fBAddFunctionWrapper\fP (const std::string &name, const DerivedWrapper &, unsigned paramsAmount)"
.br
.ti -1c
.RI "\fBFunctionWrapper\fP * \fBGetFunctionWrapper\fP (const std::string &name)"
.br
.ti -1c
.RI "bool \fBRemoveIdentifier\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBOptimize\fP ()"
.br
.ti -1c
.RI "int \fBParseAndDeduceVariables\fP (const std::string &function, int *amountOfVariablesFound=0, bool useDegrees=false)"
.br
.ti -1c
.RI "int \fBParseAndDeduceVariables\fP (const std::string &function, std::string &resultVarString, int *amountOfVariablesFound=0, bool useDegrees=false)"
.br
.ti -1c
.RI "int \fBParseAndDeduceVariables\fP (const std::string &function, std::vector< std::string > &resultVars, bool useDegrees=false)"
.br
.ti -1c
.RI "\fBFunctionParserBase\fP (const \fBFunctionParserBase\fP &)"
.br
.ti -1c
.RI "\fBFunctionParserBase\fP & \fBoperator=\fP (const \fBFunctionParserBase\fP &)"
.br
.ti -1c
.RI "void \fBForceDeepCopy\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Value_t \fBepsilon\fP ()"
.br
.ti -1c
.RI "static void \fBsetEpsilon\fP (Value_t)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Data * \fBgetParserData\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static std::pair< const char *, Value_t > \fBParseLiteral\fP (const char *)"
.br
.ti -1c
.RI "static unsigned \fBParseIdentifier\fP (const char *)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBFPoptimizer_CodeTree::CodeTree< Value_t >\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Stoched from the source code\&.
