.TH "GmpInt" 3 "Wed Jan 4 2017" "Stoched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GmpInt
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGmpIntData\fP"
.br
.ti -1c
.RI "class \fBGmpIntDataContainer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGmpInt\fP (long value)"
.br
.ti -1c
.RI "\fBGmpInt\fP (unsigned long value)"
.br
.ti -1c
.RI "\fBGmpInt\fP (int value)"
.br
.ti -1c
.RI "\fBGmpInt\fP (double value)"
.br
.ti -1c
.RI "\fBGmpInt\fP (long double value)"
.br
.ti -1c
.RI "\fBGmpInt\fP (const \fBGmpInt\fP &)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator=\fP (const \fBGmpInt\fP &)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator=\fP (signed long value)"
.br
.ti -1c
.RI "template<typename Mpz_t > void \fBget_raw_mpfr_data\fP (Mpz_t &dest_mpz_t)"
.br
.ti -1c
.RI "const char * \fBgetAsString\fP (int base=10) const"
.br
.ti -1c
.RI "long \fBtoInt\fP () const"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator+=\fP (const \fBGmpInt\fP &)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator+=\fP (long)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator\-=\fP (const \fBGmpInt\fP &)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator\-=\fP (long)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator*=\fP (const \fBGmpInt\fP &)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator*=\fP (long)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator/=\fP (const \fBGmpInt\fP &)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator/=\fP (long)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator%=\fP (const \fBGmpInt\fP &)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator%=\fP (long)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator<<=\fP (unsigned long)"
.br
.ti -1c
.RI "\fBGmpInt\fP & \fBoperator>>=\fP (unsigned long)"
.br
.ti -1c
.RI "void \fBaddProduct\fP (const \fBGmpInt\fP &value1, const \fBGmpInt\fP &value2)"
.br
.ti -1c
.RI "void \fBaddProduct\fP (const \fBGmpInt\fP &value1, unsigned long value2)"
.br
.ti -1c
.RI "void \fBsubProduct\fP (const \fBGmpInt\fP &value1, const \fBGmpInt\fP &value2)"
.br
.ti -1c
.RI "void \fBsubProduct\fP (const \fBGmpInt\fP &value1, unsigned long value2)"
.br
.ti -1c
.RI "void \fBnegate\fP ()"
.br
.ti -1c
.RI "void \fBabs\fP ()"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator+\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator+\fP (long) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator\-\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator\-\fP (long) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator*\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator*\fP (long) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator/\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator/\fP (long) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator%\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator%\fP (long) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator\-\fP () const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator<<\fP (unsigned long) const"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator>>\fP (unsigned long) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (long) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (long) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (long) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (long) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (long) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBGmpInt\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (long) const"
.br
.ti -1c
.RI "void \fBparseValue\fP (const char *value)"
.br
.ti -1c
.RI "void \fBparseValue\fP (const char *value, char **endptr)"
.br
.ti -1c
.RI "template<> void \fBget_raw_mpfr_data\fP (mpz_t &dest_mpz_t)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetDefaultNumberOfBits\fP (unsigned long)"
.br
.ti -1c
.RI "static unsigned long \fBgetDefaultNumberOfBits\fP ()"
.br
.ti -1c
.RI "static \fBGmpInt\fP \fBabs\fP (const \fBGmpInt\fP &)"
.br
.ti -1c
.RI "static \fBGmpInt\fP \fBparseString\fP (const char *str, char **endptr)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBGmpInt\fP \fBoperator+\fP (long lhs, const \fBGmpInt\fP &rhs)"
.br
.ti -1c
.RI "\fBGmpInt\fP \fBoperator\-\fP (long lhs, const \fBGmpInt\fP &rhs)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Stoched from the source code\&.
