.TH "GmpInt::GmpIntData" 3 "Wed Jan 4 2017" "Stoched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GmpInt::GmpIntData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBmRefCount\fP"
.br
.ti -1c
.RI "\fBGmpIntData\fP * \fBnextFreeNode\fP"
.br
.ti -1c
.RI "mpz_t \fBmInteger\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Stoched from the source code\&.
