.TH "Model" 3 "Wed Jan 4 2017" "Stoched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model \- Class MODEL, which holds user-specified models of stochastic systems from which realizations are to be simulated\&. A model may have variable parameters; each complete set will be stored in an object of class \fBParamset\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <model\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModel\fP ()"
.br
.RI "Default constructor for \fBModel\fP\&. "
.ti -1c
.RI "\fB~Model\fP ()"
.br
.RI "Destructor of \fBModel\fP\&. "
.ti -1c
.RI "void \fBaddVars\fP (string vars)"
.br
.RI "Add variable list to a \fBModel\fP\&. "
.ti -1c
.RI "void \fBaddEvent\fP (string functionRate)"
.br
.RI "Add \fBEvent\fP to \fBModel\fP's list of Events\&. "
.ti -1c
.RI "void \fBaddEventFct\fP (int iEvent, string function)"
.br
.RI "Add \fBEvent\fP function to specified \fBEvent\fP in \fBModel\fP\&. "
.ti -1c
.RI "double \fBuseEventFct\fP (int iEvent, int iFunction, double *stateArray)"
.br
.RI "Evaluate given function in specified \fBEvent\fP\&. "
.ti -1c
.RI "double \fBgetEventRate\fP (int iEvent, double *stateArray)"
.br
.RI "Evaluate rate function for a specified \fBEvent\fP\&. "
.ti -1c
.RI "void \fBupdateState\fP (int iEvent, double *stateArray)"
.br
.RI "Update state array by evaluating all functions of a given \fBEvent\fP\&. "
.ti -1c
.RI "void \fBupdateRates\fP (double *stateArray, double *rateArray)"
.br
.RI "Update rate for all Events in \fBModel\fP's \fBEvent\fP list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class MODEL, which holds user-specified models of stochastic systems from which realizations are to be simulated\&. A model may have variable parameters; each complete set will be stored in an object of class \fBParamset\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Model::Model ()"

.PP
Default constructor for \fBModel\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
nothing 
.RE
.PP

.SS "Model::~Model ()"

.PP
Destructor of \fBModel\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
nothing 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Model::addEvent (string functionRate)"

.PP
Add \fBEvent\fP to \fBModel\fP's list of Events\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionRate\fP is a string that defines an \fBEvent\fP's rate 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void Model::addEventFct (int iEvent, string function)"

.PP
Add \fBEvent\fP function to specified \fBEvent\fP in \fBModel\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIiEvent\fP is an int that indexes \fBEvent\fP list 
.br
\fIfunction\fP is a string that specifies \fBEvent\fP function 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void Model::addVars (string vars)"

.PP
Add variable list to a \fBModel\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvars\fP is a string used to set variables associate with a \fBModel\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "double Model::getEventRate (int iEvent, double * stateArray)"

.PP
Evaluate rate function for a specified \fBEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIiEvent\fP is an int that indexes \fBEvent\fP list 
.br
\fIstateArray\fP is a double array specifiying variable values of a function 
.RE
.PP
\fBReturns:\fP
.RS 4
evaluated rate function as a double 
.RE
.PP

.SS "void Model::updateRates (double * stateArray, double * rateArray)"

.PP
Update rate for all Events in \fBModel\fP's \fBEvent\fP list\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstateArray\fP is a double array specifiying variable values of a function 
.br
\fIrateArray\fP is a double array specifiying variable values of a rate function 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void Model::updateState (int iEvent, double * stateArray)"

.PP
Update state array by evaluating all functions of a given \fBEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIiEvent\fP is an int that indexes \fBEvent\fP list 
.br
\fIstateArray\fP is a double array specifiying variable values of a function 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "double Model::useEventFct (int iEvent, int iFunction, double * stateArray)"

.PP
Evaluate given function in specified \fBEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIiEvent\fP is an int that indexes \fBEvent\fP list 
.br
\fIiFunction\fP is an int that indexes an \fBEvent\fP's Function list 
.br
\fIstateArray\fP is a double array specifiying variable values of a function 
.RE
.PP
\fBReturns:\fP
.RS 4
evaluated function as a double 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Stoched from the source code\&.
