.TH "MpfrFloat::MpfrFloatDataContainer" 3 "Wed Jan 4 2017" "Stoched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MpfrFloat::MpfrFloatDataContainer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMpfrFloatData\fP * \fBallocateMpfrFloatData\fP (bool initToZero)"
.br
.ti -1c
.RI "void \fBreleaseMpfrFloatData\fP (\fBMpfrFloatData\fP *data)"
.br
.ti -1c
.RI "void \fBsetDefaultPrecision\fP (unsigned long bits)"
.br
.ti -1c
.RI "unsigned long \fBgetDefaultPrecision\fP () const"
.br
.ti -1c
.RI "\fBMpfrFloatData\fP * \fBconst_0\fP ()"
.br
.ti -1c
.RI "\fBMpfrFloat\fP \fBconst_pi\fP ()"
.br
.ti -1c
.RI "\fBMpfrFloat\fP \fBconst_e\fP ()"
.br
.ti -1c
.RI "\fBMpfrFloat\fP \fBconst_log2\fP ()"
.br
.ti -1c
.RI "\fBMpfrFloat\fP \fBconst_epsilon\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Stoched from the source code\&.
