.TH "YYSTYPE" 3 "Wed Jan 4 2017" "Stoched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YYSTYPE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBival\fP"
.br
.ti -1c
.RI "float \fBdval\fP"
.br
.ti -1c
.RI "char * \fBsval\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Stoched from the source code\&.
